name = "Modded Kaida 1.21.1"
author = "AaroTron9000"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ff858d635868c5f9155c86710eaf0b547c77ce9bba6dae066230103f602afd0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
