name = "Modded Kaida 1.21.1"
author = "AaroTron9000"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c05dcddea240d380a8a0cd8c20ed881188cbe5264c9addab1ed9d5f4d10117df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
